### ISSUE TITLE
Broken links in the docs

### ISSUE THREAD

**Issue by allanaaa** [omeka/classic-enduser#43]
As far as I can tell, every single relative link (inside the docs) on this page, https://omeka.org/classic/docs/GettingStarted/Feature_List/, isn't working. All the external links, and the PDF link at the beginning (which is also relative) is working fine. This problem happens a lot across the docs.

Currently a lot of relative links look like this:
```
[Library of Congress Suggest](../Plugins/Library_of_Congress_Suggest/)
[Simple Vocab](Plugins/SimpleVocab/)
[Exhibit Builder](../Plugins/ExhibitBuilder)
```

Working links look like this:
```
[CSV Import](../Plugins/CSV_Import.md)
[editing](../../Content/Item_Types.md#edit-an-existing-item-type)
``` 

Two things to note: 

- Hovering over a link in the docs won't actually show you what's happening behind the scenes; all the links look like "https://omeka.org/classic/docs/Plugins/ItemRelations/" and etc. even if they're actually `../Plugins/ItemRelations.md` in the [code](https://github.com/omeka/classic-enduser/blob/master/docs/Admin/Settings/Item_Type_Elements.md?plain=1). 
- And a link that works on the github display version (https://github.com/omeka/classic-enduser/blob/master/docs/GettingStarted/Feature_List.md) may not work on the docs, and vice-versa. 

I'm creating this issue as a sort of show-my-work, a place to refer back to my own instructions, and discussion space if needed. I'll introduce a big PR to fix links and some minor copyediting stuff across the whole of the user manual. I'm also checking and updating/removing external links, as in https://github.com/omeka/classic-enduser/pull/42. And I'm making some style/syntax-guide edits to a copy of the staff "working with the user manuals" google doc that I'll merge when they're ready.

Let me know if I've missed anything or if this doesn't seem right. Thanks!

**Comment by zerocrates** [comment]
The situation here is that internal links actually _should_ be the type that's a link to a markdown file like `../Plugins/ItemRelations.md`. Those work when viewed in Github, and also will render into working links when the site is built, and also will generate a notice if the link goes to a document that doesn't exist at build time.

The "bare" links have a variety of problems: the build-time link checker can't check them, they require an "extra" `..` layer because of the way the folder structure is used on the built site, and they don't work for users just browsing the unbuilt Github repo.
